services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"

  gradio_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OLLAMA_HOST: ollama:11434  # Service name instead of localhost
    ports:
      - "${APP_PORT:-7860}:7860"
    depends_on:
      - ollama

volumes:
  ollama_data: